title: Kenneth Foster
markdown: kramdown
theme: minima
plugins:
- jekyll-remote-theme

header_pages:
  - index.md
  
social-links:
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/kennethbfoster/" }
  - { platform: github, user_url: "https://github.com/ken-foster/" }
  - { platform: kaggle, user_url: "https://www.kaggle.com/kfoster150" }
  
