title: Kenneth Foster
description: A place to show my projects and experience
markdown: kramdown
theme: minima
plugins:
- jekyll-remote-theme

social-network-links:
  github: ken-foster
  kaggle: kfoster150
  linkedin: kennethbfoster
  
  
