title: Kenneth Foster
  
description: >
  A portolio website for Kenneth Foster

# Build Settings
theme: minima

#markdown: kramdown

#plugins:
#- jekyll-remote-theme

minima:
  social-links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/kennethbfoster/" }
    - { platform: github, user_url: "https://github.com/ken-foster/" }
    - { platform: kaggle, user_url: "https://www.kaggle.com/kfoster150" }

  header_pages:
    - index.md
