title: A data professional who is happy to help!
  
description: >
  A portolio website, hosted on Github Pages

# Build Settings
#theme: minima
#remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

# Social-links
linkedin_username: kennethbfoster
github_username: ken-foster

# Headers
header_pages:
  - index.md
