title: Main
  
description: >
  A portolio website for Kenneth Foster

# Build Settings
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

# Social-links
linkedin_username: kennethbfoster
github_username: ken-foster

# Headers
header_pages:
  - index.md
