title: Home
  
description: >
  A portolio website for Kenneth Foster

# Build Settings
theme: minima

# Social-links
linkedin_username: kfoster150
github_username: ken-foster

# Headers
header_pages:
  - index.md
