title: Main
  
description: >
  A portolio website for Kenneth Foster

# Build Settings
theme: modernist

# Social-links
linkedin_username: kennethbfoster
github_username: ken-foster

# Headers
header_pages:
  - index.md
