title: Kenneth Foster
  
description: >
  A portolio website for Kenneth Foster

# Build Settings
theme: minima

#markdown: kramdown

#plugins:
#- jekyll-remote-theme

#minima:
# social-links
linkedin_username: kfoster150
github_username: ken-foster

header_pages:
  - index.md
